import type { ComponentType } from "react";
import {
  ArrowClockwise,
  ArrowsClockwise,
  Blueprint,
  Brain,
  BracketsAngle,
  Briefcase,
  Broadcast,
  Buildings,
  BuildingOffice,
  ChartBar,
  ChartLineUp,
  Cloud,
  CloudArrowUp,
  Code,
  ComputerTower,
  Cpu,
  Database,
  Desktop,
  Detective,
  Eye,
  Factory,
  Fingerprint,
  Gear,
  Graph,
  HardDrives,
  Key,
  Lightning,
  Lock,
  LockKey,
  MagnifyingGlass,
  Network,
  Robot,
  Shield,
  ShieldCheck,
  ShieldWarning,
  Stack,
  Vault,
  WifiHigh,
  Wrench,
} from "@phosphor-icons/react/dist/ssr";

type ThumbnailIconComponent = ComponentType<{
  size?: number | string;
  weight?: "duotone" | "regular" | "bold" | "fill" | "light" | "thin";
  color?: string;
  className?: string;
}>;

/**
 * Phosphor components keyed by resolved icon name
 * (after THUMBNAIL_ICON_ALIASES). Duotone weight applied at render.
 */
export const THUMBNAIL_ICON_COMPONENTS: Record<string, ThumbnailIconComponent> = {
  ArrowClockwise,
  ArrowsClockwise,
  Blueprint,
  Brain,
  BracketsAngle,
  Briefcase,
  Broadcast,
  Buildings,
  BuildingOffice,
  ChartBar,
  ChartLineUp,
  Cloud,
  CloudArrowUp,
  Code,
  ComputerTower,
  Cpu,
  Database,
  Desktop,
  Detective,
  Eye,
  Factory,
  Fingerprint,
  Gear,
  Graph,
  HardDrives,
  Key,
  Lightning,
  Lock,
  LockKey,
  MagnifyingGlass,
  Network,
  Robot,
  Shield,
  ShieldCheck,
  ShieldWarning,
  Stack,
  Vault,
  WifiHigh,
  Wrench,
};
